package cn.yufu.posp.client.domain.model;

import java.util.Date;

/**
 * OaClientComputerInfo generated by MyEclipse Persistence Tools
 */

public class OaClientComputerInfoModel implements java.io.Serializable {

	// Fields

	private String macAddr;
	private String ipAddr;
	private String hostName;
	private String userId;
	private String createUser;
	private Date createTimestamp;
	private Date updateTimestamp;
	private String updateUser;
	private String clientId;
	private String merId;

	// Constructors

	/** default constructor */
	public OaClientComputerInfoModel() {
	}

	/** minimal constructor */
	public OaClientComputerInfoModel(String macAddr) {
		this.macAddr = macAddr;
	}

	/** full constructor */
	public OaClientComputerInfoModel(String macAddr, String ipAddr, String hostName,
			String userId, String createUser, Date createTimestamp,
			Date updateTimestamp, String updateUser, String clientId,
			String merId) {
		this.macAddr = macAddr;
		this.ipAddr = ipAddr;
		this.hostName = hostName;
		this.userId = userId;
		this.createUser = createUser;
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
		this.updateUser = updateUser;
		this.clientId = clientId;
		this.merId = merId;
	}

	// Property accessors

	public String getMacAddr() {
		return this.macAddr;
	}

	public void setMacAddr(String macAddr) {
		this.macAddr = macAddr;
	}

	public String getIpAddr() {
		return this.ipAddr;
	}

	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public String getMerId() {
		return this.merId;
	}

	public void setMerId(String merId) {
		this.merId = merId;
	}

}